---
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: solution.py

container:
  image: apluslms/grade-python:math-3.7-4.2-3.5
  mount: exercises/embedded_plot
  cmd: graderutils
