---
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: solution.py

container:
  image: apluslms/grade-python:3.7-3.5-3.4
  mount: exercises/embedded_plot
  cmd: graderutils
