---
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: functions.py

container:
  image: apluslms/grade-python:3.7-3.5-3.4
  mount: exercises/hello_python_graderutils
  cmd: graderutils
